### ISSUE TITLE
Bəzi xırda səhvlər

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Sevinj-joy/Sevinj-joy-PragmatechFoundationProject#12]
**[Burada](https://github.com/Sevinj-joy/Sevinj-joy-PragmatechFoundationProject/blob/master/Works/Porto_navb/style.css#L22)** 1 vergül qoyulmalıdır.

**Comment by isbendiyarovanezrin** [comment]
CSS-də sətirlər arasında çoxlu ara, boşluq qoymaq oxunaqlılığı azaldır, səliqəsiz görünür. Məsələn, **[bu](https://github.com/Sevinj-joy/Sevinj-joy-PragmatechFoundationProject/blob/master/Works/Porto_navb/style.css#L38)** hissədəki kimi.

**Comment by Sevinj-joy** [comment]
aydindir nezere aldim fikirlerinizi
