### ISSUE TITLE
GitHubda aktiv olun

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Sevinj-joy/Sevinj-joy-PragmatechFoundationProject#13]
**2 gündür** GitHuba heç nə əlavə etməmisiniz. 1 sətir kod belə yazsanız GitHuba əlavə edin. Bu çox vacibdir. Əlavə edin ki, baxıb səhvlərinizi deyə bilim.

**Comment by Sevinj-joy** [comment]
tamam tesekkurler
