### ISSUE TITLE
Bu testi işləyin

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Sevinj-joy/Sevinj-joy-PragmatechFoundationProject#20]
25 sualdan ibarət **[bu](https://www.w3schools.com/js/js_quiz.asp)** JavaScript testini işləyə bilərsiniz. Belə testlər işləmək JavaScript haqqında nə qədər bildiyinizi və ya bilmədiyinizi öyrənmək üçün yaxşı yoldur.

**Comment by Sevinj-joy** [comment]
Nezrin xanim isledim neticem 75%

**Comment by isbendiyarovanezrin** [comment]
Əla!🙂
