### ISSUE TITLE
Responsiv dizayn üçün qaynaqlar 

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Sevinj-joy/Sevinj-joy-PragmatechFoundationProject#52]
Mövzu ilə bağlı aşağıdakı qaynaqları analiz edə bilərsiniz.

- **[Birinci qaynaq](https://www.w3schools.com/css/css_rwd_mediaqueries.asp)**
- **[İkinci qaynaq](https://youtu.be/S8dQjPf0GyM)**
- **[Üçüncü qaynaq](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Responsive_Design)**
- **[Dördüncü qaynaq](https://www.w3schools.com/css/css_rwd_images.asp)**
- **[Beşinci qaynaq](https://www.w3schools.com/html/html_responsive.asp)**
- **[Altıncı qaynaq](https://youtu.be/zryaHix-yFA)**

**Comment by Sevinj-joy** [comment]
Cox sagolun

1 apr 2022, C. 16:12 tarixində Nəzrin İsbəndiyarova <
***@***.***> yazdı:
